apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankinsappdeployment
spec:
  selector:
    matchLabels:
      app: bankingapp
  replicas: 2
  template:
    metadata:
      labels:
        app: bankingapp
    spec:
      containers:
        - name: bankingapp
          image: raslenmissaoui061/raslenshack:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bankingapp-ssvc
spec:
  selector:
    app: bankingapp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: NodePort
