apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: bankinsappdeployment
spec:
  selector:
    matchLabels:
      app: bankingappp
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: bankingapp
    spec:
      containers:
        - name: bankingapp
          image: raslenmissaoui061/raslenshack:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: bankingapp-ssvc
spec:
  selector:
    app: bankingapp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: NodePort # type of the service.
